In [3]:
#Numpy

import numpy as np

data1 = [1,2,3,4,5]
array1 = np.array(data1)
print(array1)

array1.shape

[1 2 3 4 5]


(5,)

In [44]:
data2 = [1 , 2 , 3 , 4 , 5.5]
array2 = np.array(data2)
print(array2)

array2.shape

[1.  2.  3.  4.  5.5]


(5,)

In [45]:
data3 = [1 , 2 , 3 , 4 , '새우깡']
array3 = np.array(data3)
print(array3)

array3.shape

['1' '2' '3' '4' '새우깡']


(5,)

In [5]:
array4 = np.array( [1,2,3,4,5])
print(array4)

[1 2 3 4 5]


In [47]:
print('array1:',array1.dtype)
print('array2:',array2.dtype)
print('array3:',array3.dtype)
print('array4:',array4.dtype)

array1: int32
array2: float64
array3: <U11
array4: int32


In [7]:
print(np.zeros((3,4)))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [49]:
print(np.ones((3,4), dtype=np.int16))

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [50]:
print(np.arange(10, 30, 5))

[10 15 20 25]


In [51]:
x = np.linspace(0, 99, 100) # 0~99까지 100등분
print(x)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35.
 36. 37. 38. 39. 40. 41. 42. 43. 44. 45. 46. 47. 48. 49. 50. 51. 52. 53.
 54. 55. 56. 57. 58. 59. 60. 61. 62. 63. 64. 65. 66. 67. 68. 69. 70. 71.
 72. 73. 74. 75. 76. 77. 78. 79. 80. 81. 82. 83. 84. 85. 86. 87. 88. 89.
 90. 91. 92. 93. 94. 95. 96. 97. 98. 99.]


In [52]:
array5 = np.array( [ [1,2,3],[3,4,5],[5,6,7] ])
print(array5)

array5.shape

[[1 2 3]
 [3 4 5]
 [5 6 7]]


(3, 3)

In [53]:
array6=np.arange(12).reshape(4,3)
print(array6)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [54]:
array7=array6.reshape(2,6)
print(array7)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [55]:
array8=array6.reshape(-1,1)
print(array8)

[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]]


In [56]:
# reshape( ) : 복사본의 형태를 변경
# resize( ) : 원본의 데이터를 변경

In [89]:
array1 = np.array([ [1,2],[3,4]])
print(array1)

array2 = np.array([ [5,6],[7,8]])
print(array2)
print()
#vstack( ) 
print('-vstack:','\n',np.vstack((array1,array2)))
print()
#hstack( )
print('-hstack:''\n',np.hstack((array1,array2)))

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]

-vstack: 
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

-hstack:
 [[1 2 5 6]
 [3 4 7 8]]


In [57]:
import numpy as np
name = np.array(['홍길동','일지매','전우치'])
loc = np.array(['서울','부산','대전'])
print(name)
print(loc)
print()

all_data = np.column_stack( (name,loc))
print(all_data)

['홍길동' '일지매' '전우치']
['서울' '부산' '대전']

[['홍길동' '서울']
 ['일지매' '부산']
 ['전우치' '대전']]


In [58]:
array1 = np.array( [ [1,2,3] , [4,5,6] ])
print(array1)

print("\n")

array2 = np.array( [ [10,20,30] , [40,50,60] ])
print(array2)

[[1 2 3]
 [4 5 6]]


[[10 20 30]
 [40 50 60]]


In [59]:
array1 + array2

array([[11, 22, 33],
       [44, 55, 66]])

In [60]:
array2 - array1

array([[ 9, 18, 27],
       [36, 45, 54]])

In [61]:
array1 * array2

array([[ 10,  40,  90],
       [160, 250, 360]])

In [64]:
array2 / array1

array([[10., 10., 10.],
       [10., 10., 10.]])

In [65]:
a = np.array([2,3,4,5])
b = np.array([8,5,4])
c = np.array([5,4,6,8,3])
ax,bx,cx = np.ix_(a,b,c)
print(ax)
print(bx)


[[[2]]

 [[3]]

 [[4]]

 [[5]]]
[[[8]
  [5]
  [4]]]


In [66]:
print(ax + bx)

[[[10]
  [ 7]
  [ 6]]

 [[11]
  [ 8]
  [ 7]]

 [[12]
  [ 9]
  [ 8]]

 [[13]
  [10]
  [ 9]]]


In [67]:
array1 = np.array([1,2,3,4,5])
print('전체값:' , array1)
print('1번째값:' , array1[0])
print('3번째값:' , array1[2])
print('2-4번째값:',array1[1:4])

전체값: [1 2 3 4 5]
1번째값: 1
3번째값: 3
2-4번째값: [2 3 4]


In [68]:
array2 = np.array([ [1,2,3],[4,5,6],[7,8,9] ])
print(array2)
print('\n')
print(array2[2,2])


[[1 2 3]
 [4 5 6]
 [7 8 9]]


9


In [69]:
array1 = np.random.randn(3,3)
array1

array([[ 0.04628569,  1.65260312,  0.7902929 ],
       [ 1.85636468, -0.85761993,  0.9131526 ],
       [ 0.71048277,  0.56669171,  1.10765611]])

In [70]:
import numpy as np

np.abs(array1)

array([[0.04628569, 1.65260312, 0.7902929 ],
       [1.85636468, 0.85761993, 0.9131526 ],
       [0.71048277, 0.56669171, 1.10765611]])

In [71]:
np.square(array1)

array([[2.14236551e-03, 2.73109708e+00, 6.24562871e-01],
       [3.44608981e+00, 7.35511937e-01, 8.33847664e-01],
       [5.04785771e-01, 3.21139495e-01, 1.22690205e+00]])

In [72]:
np.ceil(array1)

array([[ 1.,  2.,  1.],
       [ 2., -0.,  1.],
       [ 1.,  1.,  2.]])

In [73]:
np.floor(array1)

array([[ 0.,  1.,  0.],
       [ 1., -1.,  0.],
       [ 0.,  0.,  1.]])

In [74]:
sum_ex = np.array([1,3,5,7,9])
np.sum(sum_ex)

25

In [75]:
np.cumsum(sum_ex)

array([ 1,  4,  9, 16, 25], dtype=int32)

In [76]:
np.isnan(array1)

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [77]:
np.isinf(array1)

array([[False, False, False],
       [False, False, False],
       [False, False, False]])